spring:
  application:
    name: spring_boot_data_udemy
  datasource:
    url: jdbc:postgresql://localhost:5432/udemy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

